InsaatSite/Models/mesaj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InsaatSite.Models
{
    public class mesaj
    {
        public int id { get; set; }
        public string konu { get; set; }
        public string message { get; set; }
        
    }
}

InsaatSite/Controllers/PanelController.cs
using InsaatSite.Models;
using InsaatSite.Repositories;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InsaatSite.Controllers
{
  
    public class PanelController : Controller
    {
        CalısanRepository calısanRepository = new CalısanRepository();
        HizmetRepository hizmetRepository = new HizmetRepository();
        ProjeRepository projeRepository = new ProjeRepository();
        KategoriRepository kategoriRepository = new KategoriRepository();
        HaberRepository haberRepository = new HaberRepository();
        SiteRepository siteRepository = new SiteRepository();
        SliderRepository sliderRepository = new SliderRepository();
        MesajRepository mesajRepository = new MesajRepository();


       
        public ActionResult Index()
        {
            return View();
        }

       
        public PartialViewResult CalisanListelePartial()
        {
            List<calısan> calisanList = calısanRepository.Listele();

            return PartialView(calisanList);
        }
        public ActionResult CalisanListele()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris","Login");
            }
            return View();
        }
        public ActionResult CalısanEkle()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            return View();
        }

        public ActionResult CalısanEkleDb(calısan gelen, HttpPostedFileBase calısanResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/calisan/");

            calısanRepository.CalısanEkle(gelen, calısanResim, yol);

            return RedirectToAction("CalisanListele");

        }

        public ActionResult CalısanSil(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }

            calısanRepository.CalısanSil(id);
            return RedirectToAction("CalisanListele");
        }
        public ActionResult CalısanGuncelle(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            calısan calis = calısanRepository.idyegorecek(id);
            return View(calis);
        }
        public ActionResult CalısanGuncelleDb(calısan gelen, HttpPostedFileBase calısanResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/calisan/");
            calısanRepository.CalısanGuncelleDb(gelen, calısanResim, yol);
            return RedirectToAction("CalisanListele");
        }

        public ActionResult HizmetListele()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            List<hizmet> hizmetlist = hizmetRepository.Listele();
            return View(hizmetlist);
        }

        public ActionResult HizmetEkle()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            return View();
        }
        public ActionResult HizmetEkleDb(hizmet gelen, HttpPostedFileBase hizmetResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/hizmet/");
            hizmetRepository.HizmetEkleDb(gelen, hizmetResim, yol);

            return RedirectToAction("HizmetListele");
        }

        public ActionResult HizmetSil(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            hizmetRepository.HizmetSil(id);
            return RedirectToAction("HizmetListele");
        }


        public ActionResult HizmetGuncelle(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            hizmet hzmt = hizmetRepository.idyegorecek(id);
            return View(hzmt);
        }

        public ActionResult HizmetGuncelleDb(hizmet gelen, HttpPostedFileBase hizmetResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/hizmet/");
            hizmetRepository.HizmetGuncelleDb(gelen, hizmetResim, yol);
            return RedirectToAction("HizmetListele");
        }
        public ActionResult ProjeListele()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            List<proje> projelist = projeRepository.Listele();
            return View(projelist);
        }
        public PartialViewResult KategoriDropdown()
        {
            
            List<kategori> kategoriList = kategoriRepository.Listele();

            ViewBag.KategoriListem = kategoriList;
            return PartialView();
        }
        public ActionResult ProjeEkle()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            return View();
        }
        public ActionResult ProjeEkleDb(proje gelen, HttpPostedFileBase projeResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/proje/");
            projeRepository.ProjeEkleDb(gelen, projeResim, yol);
            return RedirectToAction("ProjeListele");
        }
        public ActionResult ProjeSil(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            projeRepository.ProjeSil(id);

            return RedirectToAction("ProjeListele");
        }

        public ActionResult ProjeGuncelle(int? id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            proje projecik = new proje();
            if (id.HasValue)
            {
                projecik = projeRepository.idyegorecek(id.Value);
            }
            return View(projecik);
        }
        public ActionResult ProjeGuncelleDb(proje gelen, HttpPostedFileBase projeResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            string yol = Server.MapPath("~/resimler/proje/");
            projeRepository.ProjeGuncelleDb(gelen, projeResim, yol);
            return RedirectToAction("ProjeListele");
        }

        public ActionResult KategoriListele()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            List<kategori> kategoriList = kategoriRepository.Listele();
            return View(kategoriList);
        }

        public ActionResult KategoriEkle()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            return View();
        }

        public ActionResult KategoriEkleDb(kategori gelenkategori)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            kategoriRepository.Ekle(gelenkategori);
            return RedirectToAction("KategoriListele");
        }

        public ActionResult KategoriSil(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            kategoriRepository.Sil(id);
            return RedirectToAction("KategoriListele");
        }


        public ActionResult KategoriGuncelle(int id)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            kategori kategoricik = kategoriRepository.IdyeGoreCek(id);

            return View(kategoricik);
        }
        public ActionResult KategoriGuncelleDb(kategori kategoricik)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            kategoriRepository.Guncelle(kategoricik);

            return RedirectToAction("KategoriListele");
        }

        public ActionResult HaberListele()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            List<haber> haberList = haberRepository.Listele();


            return View(haberList);
        }

        public ActionResult HaberEkle()
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }
            return View();
        }


        public ActionResult HaberEkleDb(haber gelen, HttpPostedFileBase haberResim)
        {
            if (Session["kullaniciAdi"] == null)
            {
                return RedirectToAction("Giris", "Login");
            }

InsaatSite/Views/Panel/CalısanEkle.cshtml
@model InsaatSite.Models.calısan

@{
	ViewBag.Title = "CalısanEkle";
	Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>Çalışan Ekle</h2>

@using (Html.BeginForm("CalısanEkleDb", "Panel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>calısan</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.ad, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.soyad, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.unvan, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.unvan, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.unvan, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2"> Dosya yükle </label>
			<div class="col-md-10">
				<input id="pic" class="form-control" type="file" name="calısanResim" />
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.facebookLink, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.facebookLink, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.facebookLink, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.instagramLink, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.instagramLink, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.instagramLink, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.twitterLink, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.twitterLink, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.twitterLink, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Kaydet" class="btn btn-info" />
			</div>
		</div>
	</div>
}


<div id="calisanList">
	@Html.Action("CalisanListelePartial", "Panel")
</div>

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/CalısanGuncelle.cshtml
@model InsaatSite.Models.calısan

@{
    ViewBag.Title = "CalısanGuncelle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>Çalışanan Guncelle</h2>
@using (Html.BeginForm("CalısanGuncelleDb","Panel",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>calısan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

	<input type="hidden" name="id" value="@Model.id" />
		
        <div class="form-group">
            @Html.LabelFor(model => model.ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.unvan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.unvan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.unvan, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			<label class="control-label col-md-2"> Dosya yükle </label>
			<div class="col-md-10">
				<input class="form-control" type="file" name="calısanResim" />
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.facebookLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.facebookLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.facebookLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.instagramLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.instagramLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.instagramLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.twitterLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.twitterLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.twitterLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/HaberEkle.cshtml
@model InsaatSite.Models.haber

@using (Html.BeginForm("HaberEkleDb","Panel",FormMethod.Post,new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>haber</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.detay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.detay, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			<label class="control-label col-md-2"> Dosya yükle </label>
			<div class="col-md-10">
				<input class="form-control" type="file" name="haberResim" />
			</div>
		</div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/HaberGuncelle.cshtml
@model InsaatSite.Models.haber
@{
	Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
@using (Html.BeginForm("HaberGuncelleDb", "Panel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<input type="hidden" name="id" value="@Model.id" />

	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>haber</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.baslik, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.baslik, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.spot, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.spot, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.spot, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.detay, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.detay, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.detay, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2"> Dosya yükle </label>
			<div class="col-md-10">
				<input class="form-control" type="file" name="haberResim" />
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Kaydet" class="btn btn-warning" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/HaberListele.cshtml
@model IEnumerable<InsaatSite.Models.haber>
@{
	Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<p>
    @Html.ActionLink("Haber Ekle", "HaberEkLe","Panel")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.spot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.detay)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.resim)
        </th>
        <th>İşlem</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.baslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.spot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.detay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.resim)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "HaberGuncelle", new {  id=item.id},new { @class="btn btn-warning"}) 
            @Html.ActionLink("Sil", "HaberSil", new { id=item.id},new { @class="btn btn-info"})
        </td>
    </tr>
}

</table>

InsaatSite/Views/Panel/HizmetEkle.cshtml
@model InsaatSite.Models.hizmet

@{
    ViewBag.Title = "HizmetEkle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>Hizmet Ekle</h2>

@using (Html.BeginForm("HizmetEkleDb","Panel",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Hizmet</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.baslik, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.baslik, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.baslik, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.acıklama, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.acıklama, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.acıklama, "", new { @class = "text-danger" })
		</div>
	</div>


	<div class="form-group">
		<label class="control-label col-md-2"> Dosya yükle </label>
		<div class="col-md-10">
			<input class="form-control" type="file" name="hizmetResim" />
		</div>
	</div>


	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Kaydet" class="btn btn-info" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/HizmetListele.cshtml
@model IEnumerable<InsaatSite.Models.hizmet>

@{
    ViewBag.Title = "HizmetListele";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>HizmetListele</h2>

<p>
    @Html.ActionLink("Hizmet Ekle", "HizmetEkleDb",	"Panel")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.acıklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.resim)
        </th>
        <th></th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.baslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.acıklama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.resim)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "HizmetGuncelle","Panel", new {id=item.id },new { @class = "btn btn-warning btn xs" }) 
            
            @Html.ActionLink("Sil", "HizmetSil","Panel" , new {  id=item.id },new { @class = "btn btn-info btn xs" })
        </td>
    </tr>
}

</table>

InsaatSite/Views/Panel/Index.cshtml
@{
	Layout = "~/Views/Shared/_PanelLayout.cshtml";

}

InsaatSite/Views/Panel/KategoriDropdown.cshtml
@using InsaatSite.Models


<div class="form-group">
	<label class="control-label col-md-2">Kategori Adı</label>
	<div class="col-md-10">
		<select class="form-control" name="kategori">
			@{
				foreach (var item in (List<kategori>)ViewBag.KategoriListem)
				{
					<option value="@item.id"> @item.Kategori </option>

				}
			}
		</select>

	</div>
</div>

InsaatSite/Views/Panel/KategoriEkle.cshtml
@model InsaatSite.Models.kategori

@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>Kategori Ekle</h2>

@using (Html.BeginForm("KategoriEkleDb","Panel")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>kategori</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Kategori, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

InsaatSite/Views/Panel/KategoriGuncelle.cshtml
@model InsaatSite.Models.kategori

@{
	ViewBag.Title = "KategoriGuncelle";
	Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<h2>Kategori Guncelle</h2>

@using (Html.BeginForm("KategoriGuncelleDb", "Panel"))

{
	<input type="hidden" name="id" value="@Model.id" />

	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>kategori</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Kategori, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Kaydet" class="btn btn-warning" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>